baseURL = 'https://JB-électricité.fr/'

# Language (code)settings
languageCode = 'en-us'
title = 'J/B Électricité'
theme = 'hugo-initio'
favicon = "/images/JBéléctricité.png" 
enableRobotsTXT = true
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Will give values to .Lastmod etc.
enableGitInfo = true
enableEmoji = true

[languages]
[languages.en]
description = ""
languageName ="French"

# Weight used for sorting.
weight = 1

############################## NAVIGATION ###############################

[[menu.main]]
  name = "JB-Électricité"
  url= "/"
  weight = 3

[[menu.main]]
  name = "A propos"
  url= "/A_propos/"
  weight = 1

[[menu.main]]
  name = "Galerie"
  url = "/Galerie/"
  weight = 1

[[menu.main]]
  name = "Devis"
  url = "/Devis/"
  weight = 1

[[menu.main]]
  name = "Rendez-vous"
  url = "/Rendez-vous/"
  weight = 1


#################### default parameters ################################

[params]
author = "GANitak @github/GANitak"
description = "Electrician (25)"
background = ""
email = "jordanblanc.elec@gmail.com"
showFooterContact = true
showFooterFollowMe = true
phone = "06.07.81.42.63"
address = "26 Grande Rue, 39700 Rans"
year = 2023
favicon = "/images/favicon-96x96.png"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/GANitak/Sparky/issues"

# Date format "DD-MM-YYYY"
#DateForm = "12-09-2023"

#Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = ""

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# defaultTheme: light
defaultTheme = "dark"
#defaultTheme: auto # to switch between dark or light according to browser theme

############################# SOCIALS ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/GANitak"
footer = false
[[params.social]]
	title = "email"
	url = "mailto:jordanblanc.elec@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+name-of-account"
    icon = "fab fa-google-plus-square"
    footer = true
    sharethis = true
    network = "googleplus"

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]

# markup 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "monokailight"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true